name: Auto Assign Authors

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    steps:
      - name: Auto assign author to issues
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const author = issue.user.login;
            
            // 현재 assignees 확인
            const currentAssignees = issue.assignees.map(assignee => assignee.login);
            
            // 작성자가 assignee에 없으면 추가
            if (!currentAssignees.includes(author)) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                assignees: [author]
              });
              
              console.log(`✅ Assigned issue #${issue.number} to author: ${author}`);
            } else {
              console.log(`ℹ️ Issue #${issue.number} already assigned to author: ${author}`);
            }
      
      - name: Auto assign author to pull requests
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const author = pr.user.login;
            
            // 현재 assignees 확인
            const currentAssignees = pr.assignees.map(assignee => assignee.login);
            
            // 작성자가 assignee에 없으면 추가
            if (!currentAssignees.includes(author)) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                assignees: [author]
              });
              
              console.log(`✅ Assigned PR #${pr.number} to author: ${author}`);
            } else {
              console.log(`ℹ️ PR #${pr.number} already assigned to author: ${author}`);
            }