name: Auto Label Issues and PRs

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    steps:
      - name: Add MCP label to issues starting with MCP
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const title = issue.title.toLowerCase();
            
            // MCP로 시작하는 이슈인지 확인
            if (title.startsWith('mcp')) {
              // 현재 라벨 확인
              const currentLabels = issue.labels.map(label => label.name);
              
              // 'mcp test' 라벨이 없으면 추가
              if (!currentLabels.includes('mcp test')) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ['mcp test']
                });
                
                console.log(`Added 'mcp test' label to issue #${issue.number}: ${issue.title}`);
              }
            }
      
      - name: Add MCP label to PRs starting with MCP
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title.toLowerCase();
            
            // MCP로 시작하는 PR인지 확인
            if (title.startsWith('mcp')) {
              // 현재 라벨 확인
              const currentLabels = pr.labels.map(label => label.name);
              
              // 'mcp test' 라벨이 없으면 추가
              if (!currentLabels.includes('mcp test')) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  labels: ['mcp test']
                });
                
                console.log(`Added 'mcp test' label to PR #${pr.number}: ${pr.title}`);
              }
            }